[tool.pytest.ini_options]
pythonpath = ["Module_1"]
testpaths = ["tests"]
filterwarnings = [
    "ignore:invalid value encountered in:RuntimeWarning:",
    "ignore:RepresentationMixin:DeprecationWarning",
]
